import { createSlice, PayloadAction } from '@reduxjs/toolkit';
// Define the shape of the timer's state
interface TimerState {
 duration: number;
 remainingTime: number;
}
// Initial state for the timer
const initialState: TimerState = {
 duration: 60,
 remainingTime: 60,
};
// Create a slice for the timer
const timerSlice = createSlice({
 name: 'timer',
 initialState,
 reducers: {
  // Action to set a new duration for the timer
  setDuration(state, action: PayloadAction<number>) {
   state.duration = action.payload;
   state.remainingTime = action.payload;
  },
  // Action to decrement the remaining time by 1 second
  tick(state) {
   state.remainingTime -= 1;
  },
  // Action to reset the remaining time to the original duration
  reset(state) {
   state.remainingTime = state.duration;
  },
 },
});
// Export the action creators generated by createSlice
export const { setDuration, tick, reset } = timerSlice.actions;
// Export the reducer to be included in the store
export default timerSlice.reducer;
